name: "mobile_vision.cls"
op {
  input: "data"
  input: "conv0_conv_w"
  input: "conv0_bn_b"
  output: "conv0_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "conv0_bn"
  output: "conv0"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "conv0"
  input: "xif0_0_pw_conv_w"
  input: "xif0_0_pw_bn_b"
  output: "xif0_0_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif0_0_pw_bn"
  output: "xif0_0_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_pw"
  input: "xif0_0_dw_conv_w"
  input: "xif0_0_dw_bn_b"
  output: "xif0_0_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 8
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif0_0_dw_bn"
  output: "xif0_0_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_dw"
  input: "xif0_0_pwl_conv_w"
  input: "xif0_0_pwl_bn_b"
  output: "xif0_0_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif0_0_pwl_bn"
  input: "conv0"
  output: "xif0_0"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0"
  input: "xif1_0_pw_conv_w"
  input: "xif1_0_pw_bn_b"
  output: "xif1_0_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif1_0_pw_bn"
  output: "xif1_0_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif1_0_pw"
  input: "xif1_0_dw_conv_w"
  input: "xif1_0_dw_bn_b"
  output: "xif1_0_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 48
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif1_0_dw_bn"
  output: "xif1_0_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif1_0_dw"
  input: "xif1_0_conv_w"
  input: "xif1_0_bn_b"
  output: "xif1_0_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif1_0_bn"
  input: "xif2_0_pw_conv_w"
  input: "xif2_0_pw_bn_b"
  output: "xif2_0_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_0_pw_bn"
  output: "xif2_0_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_0_pw"
  input: "xif2_0_dw_conv_w"
  input: "xif2_0_dw_bn_b"
  output: "xif2_0_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 96
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_0_dw_bn"
  output: "xif2_0_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_0_dw"
  input: "xif2_0_conv_w"
  input: "xif2_0_bn_b"
  output: "xif2_0_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_0_bn"
  input: "xif2_1_pw_conv_w"
  input: "xif2_1_pw_bn_b"
  output: "xif2_1_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_1_pw_bn"
  output: "xif2_1_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_pw"
  input: "xif2_1_dw_conv_w"
  input: "xif2_1_dw_bn_b"
  output: "xif2_1_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 128
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_1_dw_bn"
  output: "xif2_1_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_dw"
  input: "xif2_1_pwl_conv_w"
  input: "xif2_1_pwl_bn_b"
  output: "xif2_1_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif2_1_pwl_bn"
  input: "xif2_0_bn"
  output: "xif2_1"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1"
  input: "xif3_0_pw_conv_w"
  input: "xif3_0_pw_bn_b"
  output: "xif3_0_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_0_pw_bn"
  output: "xif3_0_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_0_pw"
  input: "xif3_0_dw_conv_w"
  input: "xif3_0_dw_bn_b"
  output: "xif3_0_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 192
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_0_dw_bn"
  output: "xif3_0_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_0_dw"
  input: "xif3_0_conv_w"
  input: "xif3_0_bn_b"
  output: "xif3_0_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_0_bn"
  input: "xif3_1_pw_conv_w"
  input: "xif3_1_pw_bn_b"
  output: "xif3_1_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_1_pw_bn"
  output: "xif3_1_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_pw"
  input: "xif3_1_dw_conv_w"
  input: "xif3_1_dw_bn_b"
  output: "xif3_1_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 240
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_1_dw_bn"
  output: "xif3_1_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_dw"
  input: "xif3_1_pwl_conv_w"
  input: "xif3_1_pwl_bn_b"
  output: "xif3_1_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_1_pwl_bn"
  input: "xif3_0_bn"
  output: "xif3_1"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1"
  input: "xif3_2_pw_conv_w"
  input: "xif3_2_pw_bn_b"
  output: "xif3_2_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_2_pw_bn"
  output: "xif3_2_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_pw"
  input: "xif3_2_dw_conv_w"
  input: "xif3_2_dw_bn_b"
  output: "xif3_2_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 240
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_2_dw_bn"
  output: "xif3_2_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_dw"
  input: "xif3_2_pwl_conv_w"
  input: "xif3_2_pwl_bn_b"
  output: "xif3_2_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_2_pwl_bn"
  input: "xif3_1"
  output: "xif3_2"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2"
  input: "xif3_3_pw_conv_w"
  input: "xif3_3_pw_bn_b"
  output: "xif3_3_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_3_pw_bn"
  output: "xif3_3_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_pw"
  input: "xif3_3_dw_conv_w"
  input: "xif3_3_dw_bn_b"
  output: "xif3_3_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 240
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_3_dw_bn"
  output: "xif3_3_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_dw"
  input: "xif3_3_pwl_conv_w"
  input: "xif3_3_pwl_bn_b"
  output: "xif3_3_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_3_pwl_bn"
  input: "xif3_2"
  output: "xif3_3"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3"
  input: "xif3_4_pw_conv_w"
  input: "xif3_4_pw_bn_b"
  output: "xif3_4_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_4_pw_bn"
  output: "xif3_4_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_4_pw"
  input: "xif3_4_dw_conv_w"
  input: "xif3_4_dw_bn_b"
  output: "xif3_4_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 240
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_4_dw_bn"
  output: "xif3_4_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_4_dw"
  input: "xif3_4_conv_w"
  input: "xif3_4_bn_b"
  output: "xif3_4_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_4_bn"
  input: "xif3_5_pw_conv_w"
  input: "xif3_5_pw_bn_b"
  output: "xif3_5_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_5_pw_bn"
  output: "xif3_5_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_5_pw"
  input: "xif3_5_dw_conv_w"
  input: "xif3_5_dw_bn_b"
  output: "xif3_5_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 480
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_5_dw_bn"
  output: "xif3_5_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_5_dw"
  input: "xif3_5_pwl_conv_w"
  input: "xif3_5_pwl_bn_b"
  output: "xif3_5_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_5_pwl_bn"
  input: "xif3_4_bn"
  output: "xif3_5"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_5"
  input: "xif3_6_pw_conv_w"
  input: "xif3_6_pw_bn_b"
  output: "xif3_6_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_6_pw_bn"
  output: "xif3_6_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_6_pw"
  input: "xif3_6_dw_conv_w"
  input: "xif3_6_dw_bn_b"
  output: "xif3_6_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 480
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_6_dw_bn"
  output: "xif3_6_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_6_dw"
  input: "xif3_6_pwl_conv_w"
  input: "xif3_6_pwl_bn_b"
  output: "xif3_6_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif3_6_pwl_bn"
  input: "xif3_5"
  output: "xif3_6"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_6"
  input: "xif4_0_pw_conv_w"
  input: "xif4_0_pw_bn_b"
  output: "xif4_0_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_0_pw_bn"
  output: "xif4_0_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_0_pw"
  input: "xif4_0_dw_conv_w"
  input: "xif4_0_dw_bn_b"
  output: "xif4_0_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 400
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_0_dw_bn"
  output: "xif4_0_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_0_dw"
  input: "xif4_0_conv_w"
  input: "xif4_0_bn_b"
  output: "xif4_0_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_0_bn"
  input: "xif4_1_pw_conv_w"
  input: "xif4_1_pw_bn_b"
  output: "xif4_1_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_1_pw_bn"
  output: "xif4_1_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_pw"
  input: "xif4_1_dw_conv_w"
  input: "xif4_1_dw_bn_b"
  output: "xif4_1_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 800
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_1_dw_bn"
  output: "xif4_1_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_dw"
  input: "xif4_1_pwl_conv_w"
  input: "xif4_1_pwl_bn_b"
  output: "xif4_1_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_1_pwl_bn"
  input: "xif4_0_bn"
  output: "xif4_1"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1"
  input: "xif4_2_pw_conv_w"
  input: "xif4_2_pw_bn_b"
  output: "xif4_2_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_2_pw_bn"
  output: "xif4_2_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_pw"
  input: "xif4_2_dw_conv_w"
  input: "xif4_2_dw_bn_b"
  output: "xif4_2_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 800
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_2_dw_bn"
  output: "xif4_2_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_dw"
  input: "xif4_2_pwl_conv_w"
  input: "xif4_2_pwl_bn_b"
  output: "xif4_2_pwl_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_2_pwl_bn"
  input: "xif4_1"
  output: "xif4_2"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2"
  input: "xif4_3_pw_conv_w"
  input: "xif4_3_pw_bn_b"
  output: "xif4_3_pw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_3_pw_bn"
  output: "xif4_3_pw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_3_pw"
  input: "xif4_3_dw_conv_w"
  input: "xif4_3_dw_bn_b"
  output: "xif4_3_dw_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 960
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_3_dw_bn"
  output: "xif4_3_dw"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_3_dw"
  input: "xif4_3_conv_w"
  input: "xif4_3_bn_b"
  output: "xif4_3_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_3_bn"
  input: "xif4_3_bn_1x1_conv_w"
  input: "xif4_3_bn_1x1_bn_b"
  output: "xif4_3_bn_1x1_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "xif4_3_bn_1x1_bn"
  output: "xif4_3_bn_1x1"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_3_bn_1x1"
  output: "final_avg"
  name: ""
  type: "AveragePool"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 6
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "final_avg"
  input: "pred_w"
  input: "pred_b"
  output: "pred"
  name: ""
  type: "FC"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pred"
  output: "softmax"
  name: ""
  type: "Softmax"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
external_input: "data"
external_input: "conv0_conv_w"
external_input: "conv0_bn_b"
external_input: "xif0_0_pw_conv_w"
external_input: "xif0_0_pw_bn_b"
external_input: "xif0_0_dw_conv_w"
external_input: "xif0_0_dw_bn_b"
external_input: "xif0_0_pwl_conv_w"
external_input: "xif0_0_pwl_bn_b"
external_input: "xif1_0_pw_conv_w"
external_input: "xif1_0_pw_bn_b"
external_input: "xif1_0_dw_conv_w"
external_input: "xif1_0_dw_bn_b"
external_input: "xif1_0_conv_w"
external_input: "xif1_0_bn_b"
external_input: "xif2_0_pw_conv_w"
external_input: "xif2_0_pw_bn_b"
external_input: "xif2_0_dw_conv_w"
external_input: "xif2_0_dw_bn_b"
external_input: "xif2_0_conv_w"
external_input: "xif2_0_bn_b"
external_input: "xif2_1_pw_conv_w"
external_input: "xif2_1_pw_bn_b"
external_input: "xif2_1_dw_conv_w"
external_input: "xif2_1_dw_bn_b"
external_input: "xif2_1_pwl_conv_w"
external_input: "xif2_1_pwl_bn_b"
external_input: "xif3_0_pw_conv_w"
external_input: "xif3_0_pw_bn_b"
external_input: "xif3_0_dw_conv_w"
external_input: "xif3_0_dw_bn_b"
external_input: "xif3_0_conv_w"
external_input: "xif3_0_bn_b"
external_input: "xif3_1_pw_conv_w"
external_input: "xif3_1_pw_bn_b"
external_input: "xif3_1_dw_conv_w"
external_input: "xif3_1_dw_bn_b"
external_input: "xif3_1_pwl_conv_w"
external_input: "xif3_1_pwl_bn_b"
external_input: "xif3_2_pw_conv_w"
external_input: "xif3_2_pw_bn_b"
external_input: "xif3_2_dw_conv_w"
external_input: "xif3_2_dw_bn_b"
external_input: "xif3_2_pwl_conv_w"
external_input: "xif3_2_pwl_bn_b"
external_input: "xif3_3_pw_conv_w"
external_input: "xif3_3_pw_bn_b"
external_input: "xif3_3_dw_conv_w"
external_input: "xif3_3_dw_bn_b"
external_input: "xif3_3_pwl_conv_w"
external_input: "xif3_3_pwl_bn_b"
external_input: "xif3_4_pw_conv_w"
external_input: "xif3_4_pw_bn_b"
external_input: "xif3_4_dw_conv_w"
external_input: "xif3_4_dw_bn_b"
external_input: "xif3_4_conv_w"
external_input: "xif3_4_bn_b"
external_input: "xif3_5_pw_conv_w"
external_input: "xif3_5_pw_bn_b"
external_input: "xif3_5_dw_conv_w"
external_input: "xif3_5_dw_bn_b"
external_input: "xif3_5_pwl_conv_w"
external_input: "xif3_5_pwl_bn_b"
external_input: "xif3_6_pw_conv_w"
external_input: "xif3_6_pw_bn_b"
external_input: "xif3_6_dw_conv_w"
external_input: "xif3_6_dw_bn_b"
external_input: "xif3_6_pwl_conv_w"
external_input: "xif3_6_pwl_bn_b"
external_input: "xif4_0_pw_conv_w"
external_input: "xif4_0_pw_bn_b"
external_input: "xif4_0_dw_conv_w"
external_input: "xif4_0_dw_bn_b"
external_input: "xif4_0_conv_w"
external_input: "xif4_0_bn_b"
external_input: "xif4_1_pw_conv_w"
external_input: "xif4_1_pw_bn_b"
external_input: "xif4_1_dw_conv_w"
external_input: "xif4_1_dw_bn_b"
external_input: "xif4_1_pwl_conv_w"
external_input: "xif4_1_pwl_bn_b"
external_input: "xif4_2_pw_conv_w"
external_input: "xif4_2_pw_bn_b"
external_input: "xif4_2_dw_conv_w"
external_input: "xif4_2_dw_bn_b"
external_input: "xif4_2_pwl_conv_w"
external_input: "xif4_2_pwl_bn_b"
external_input: "xif4_3_pw_conv_w"
external_input: "xif4_3_pw_bn_b"
external_input: "xif4_3_dw_conv_w"
external_input: "xif4_3_dw_bn_b"
external_input: "xif4_3_conv_w"
external_input: "xif4_3_bn_b"
external_input: "xif4_3_bn_1x1_conv_w"
external_input: "xif4_3_bn_1x1_bn_b"
external_input: "pred_w"
external_input: "pred_b"
external_output: "softmax"
