name: "mobile_vision.cls_int8_1"
op {
  input: "data"
  output: "data_NHWC"
  name: ""
  type: "NCHW2NHWC"
}
op {
  input: "data_NHWC"
  output: "data_int8"
  name: ""
  type: "Int8Quantize"
  arg {
    name: "Y_scale"
    f: 0.0186584472656
  }
  arg {
    name: "Y_zero_point"
    i: 114
  }
}
op {
  input: "data_int8"
  input: "conv0_conv_w_int8"
  input: "conv0_bn_b_int8"
  output: "conv0_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.159663466322
  }
  device_option {
  }
  engine: ""
}
op {
  input: "conv0_int8"
  input: "xif0_0_pw_conv_w_int8"
  input: "xif0_0_pw_bn_b_int8"
  output: "xif0_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0911753003371
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_pw_int8"
  input: "xif0_0_dw_conv_w_int8"
  input: "b_zero_generated_xif0_0_pw_int8"
  output: "xif0_0_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 8
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 135
  }
  arg {
    name: "Y_scale"
    f: 0.178160768397
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_dw_conv_int8"
  input: "xif0_0_pwl_conv_w_int8"
  input: "xif0_0_pwl_bn_b_int8"
  output: "xif0_0_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 134
  }
  arg {
    name: "Y_scale"
    f: 0.419987039005
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_pwl_bn_int8"
  input: "conv0_int8"
  output: "xif0_0_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.419987039005
  }
  arg {
    name: "Y_zero_point"
    i: 134
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif0_0_int8"
  input: "xif1_0_pw_conv_w_int8"
  input: "xif1_0_pw_bn_b_int8"
  output: "xif1_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.266461845729
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif1_0_pw_int8"
  input: "xif1_0_dw_conv_w_int8"
  input: "b_zero_generated_xif1_0_pw_int8"
  output: "xif1_0_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 32
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 114
  }
  arg {
    name: "Y_scale"
    f: 0.49339279474
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif1_0_dw_conv_int8"
  input: "xif1_0_conv_w_int8"
  input: "xif1_0_bn_b_int8"
  output: "xif1_0_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 107
  }
  arg {
    name: "Y_scale"
    f: 0.510646625594
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif1_0_bn_int8"
  input: "xif2_0_pw_conv_w_int8"
  input: "xif2_0_pw_bn_b_int8"
  output: "xif2_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.190321929826
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_0_pw_int8"
  input: "xif2_0_dw_conv_w_int8"
  input: "b_zero_generated_xif2_0_pw_int8"
  output: "xif2_0_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 96
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 133
  }
  arg {
    name: "Y_scale"
    f: 0.218607943666
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_0_dw_conv_int8"
  input: "xif2_0_conv_w_int8"
  input: "xif2_0_bn_b_int8"
  output: "xif2_0_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 137
  }
  arg {
    name: "Y_scale"
    f: 0.313559797698
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_0_bn_int8"
  input: "xif2_1_pw_conv_w_int8"
  input: "xif2_1_pw_bn_b_int8"
  output: "xif2_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0867919328184
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_pw_int8"
  input: "xif2_1_dw_conv_w_int8"
  input: "b_zero_generated_xif2_1_pw_int8"
  output: "xif2_1_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 128
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 133
  }
  arg {
    name: "Y_scale"
    f: 0.103163296569
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_dw_conv_int8"
  input: "xif2_1_pwl_conv_w_int8"
  input: "xif2_1_pwl_bn_b_int8"
  output: "xif2_1_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 121
  }
  arg {
    name: "Y_scale"
    f: 0.230974818211
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_pwl_bn_int8"
  input: "xif2_0_bn_int8"
  output: "xif2_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.319621725643
  }
  arg {
    name: "Y_zero_point"
    i: 140
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_1_int8"
  input: "xif2_2_pw_conv_w_int8"
  input: "xif2_2_pw_bn_b_int8"
  output: "xif2_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0776755846046
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_2_pw_int8"
  input: "xif2_2_dw_conv_w_int8"
  input: "b_zero_generated_xif2_2_pw_int8"
  output: "xif2_2_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 128
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 127
  }
  arg {
    name: "Y_scale"
    f: 0.0823355581246
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_2_dw_conv_int8"
  input: "xif2_2_pwl_conv_w_int8"
  input: "xif2_2_pwl_bn_b_int8"
  output: "xif2_2_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 123
  }
  arg {
    name: "Y_scale"
    f: 0.242814606311
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_2_pwl_bn_int8"
  input: "xif2_1_int8"
  output: "xif2_2_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.326149914311
  }
  arg {
    name: "Y_zero_point"
    i: 135
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif2_2_int8"
  input: "xif3_0_pw_conv_w_int8"
  input: "xif3_0_pw_bn_b_int8"
  output: "xif3_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.106306397329
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_0_pw_int8"
  input: "xif3_0_dw_conv_w_int8"
  input: "b_zero_generated_xif3_0_pw_int8"
  output: "xif3_0_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 192
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 124
  }
  arg {
    name: "Y_scale"
    f: 0.0895067027971
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_0_dw_conv_int8"
  input: "xif3_0_conv_w_int8"
  input: "xif3_0_bn_b_int8"
  output: "xif3_0_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 110
  }
  arg {
    name: "Y_scale"
    f: 0.211591473748
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_0_bn_int8"
  input: "xif3_1_pw_conv_w_int8"
  input: "xif3_1_pw_bn_b_int8"
  output: "xif3_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.069632769698
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_pw_int8"
  input: "xif3_1_dw_conv_w_int8"
  input: "b_zero_generated_xif3_1_pw_int8"
  output: "xif3_1_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 133
  }
  arg {
    name: "Y_scale"
    f: 0.0382994483499
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_dw_conv_int8"
  input: "xif3_1_pwl_conv_w_int8"
  input: "xif3_1_pwl_bn_b_int8"
  output: "xif3_1_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 131
  }
  arg {
    name: "Y_scale"
    f: 0.147692616781
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_pwl_bn_int8"
  input: "xif3_0_bn_int8"
  output: "xif3_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.236043802897
  }
  arg {
    name: "Y_zero_point"
    i: 134
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_1_int8"
  input: "xif3_2_pw_conv_w_int8"
  input: "xif3_2_pw_bn_b_int8"
  output: "xif3_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0512372757773
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_pw_int8"
  input: "xif3_2_dw_conv_w_int8"
  input: "b_zero_generated_xif3_2_pw_int8"
  output: "xif3_2_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 148
  }
  arg {
    name: "Y_scale"
    f: 0.0386879266477
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_dw_conv_int8"
  input: "xif3_2_pwl_conv_w_int8"
  input: "xif3_2_pwl_bn_b_int8"
  output: "xif3_2_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 158
  }
  arg {
    name: "Y_scale"
    f: 0.227086953556
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_pwl_bn_int8"
  input: "xif3_1_int8"
  output: "xif3_2_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.24190123315
  }
  arg {
    name: "Y_zero_point"
    i: 138
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_2_int8"
  input: "xif3_3_pw_conv_w_int8"
  input: "xif3_3_pw_bn_b_int8"
  output: "xif3_3_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0616645340734
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_pw_int8"
  input: "xif3_3_dw_conv_w_int8"
  input: "b_zero_generated_xif3_3_pw_int8"
  output: "xif3_3_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 157
  }
  arg {
    name: "Y_scale"
    f: 0.0683218114516
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_dw_conv_int8"
  input: "xif3_3_pwl_conv_w_int8"
  input: "xif3_3_pwl_bn_b_int8"
  output: "xif3_3_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 101
  }
  arg {
    name: "Y_scale"
    f: 0.364834295535
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_pwl_bn_int8"
  input: "xif3_2_int8"
  output: "xif3_3_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.393671910903
  }
  arg {
    name: "Y_zero_point"
    i: 110
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif3_3_int8"
  input: "xif4_0_pw_conv_w_int8"
  input: "xif4_0_pw_bn_b_int8"
  output: "xif4_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.132241950118
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_0_pw_int8"
  input: "xif4_0_dw_conv_w_int8"
  input: "b_zero_generated_xif4_0_pw_int8"
  output: "xif4_0_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 95
  }
  arg {
    name: "Y_scale"
    f: 0.116393235151
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_0_dw_conv_int8"
  input: "xif4_0_conv_w_int8"
  input: "xif4_0_bn_b_int8"
  output: "xif4_0_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 118
  }
  arg {
    name: "Y_scale"
    f: 0.19167546291
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_0_bn_int8"
  input: "xif4_1_pw_conv_w_int8"
  input: "xif4_1_pw_bn_b_int8"
  output: "xif4_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0640134295882
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_pw_int8"
  input: "xif4_1_dw_conv_w_int8"
  input: "b_zero_generated_xif4_1_pw_int8"
  output: "xif4_1_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 576
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 180
  }
  arg {
    name: "Y_scale"
    f: 0.0782555673637
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_dw_conv_int8"
  input: "xif4_1_pwl_conv_w_int8"
  input: "xif4_1_pwl_bn_b_int8"
  output: "xif4_1_pwl_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 81
  }
  arg {
    name: "Y_scale"
    f: 0.393822524127
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_pwl_bn_int8"
  input: "xif4_0_bn_int8"
  output: "xif4_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.529844994638
  }
  arg {
    name: "Y_zero_point"
    i: 76
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_1_int8"
  input: "xif4_2_pw_conv_w_int8"
  input: "xif4_2_pw_bn_b_int8"
  output: "xif4_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.14929021487
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_pw_int8"
  input: "xif4_2_dw_conv_w_int8"
  input: "b_zero_generated_xif4_2_pw_int8"
  output: "xif4_2_dw_conv_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 131
  }
  arg {
    name: "Y_scale"
    f: 0.0717710981182
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_dw_conv_int8"
  input: "xif4_2_conv_w_int8"
  input: "xif4_2_bn_b_int8"
  output: "xif4_2_bn_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 132
  }
  arg {
    name: "Y_scale"
    f: 0.137077870088
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_bn_int8"
  input: "xif4_2_bn_1x1_conv_w_int8"
  input: "xif4_2_bn_1x1_bn_b_int8"
  output: "xif4_2_bn_1x1_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.15287628913
  }
  device_option {
  }
  engine: ""
}
op {
  input: "xif4_2_bn_1x1_int8"
  output: "final_avg_int8"
  name: ""
  type: "Int8AveragePool"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_scale"
    f: 0.15287628913
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  device_option {
  }
  engine: ""
}
op {
  input: "final_avg_int8"
  input: "pred_w_int8"
  input: "pred_b_int8"
  output: "pred_int8"
  name: ""
  type: "Int8FC"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_zero_point"
    i: 90
  }
  arg {
    name: "Y_scale"
    f: 0.168010472316
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pred_int8"
  output: "softmax_int8"
  name: ""
  type: "Int8Softmax"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_scale"
    f: 0.00390625
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  device_option {
  }
  engine: ""
}
op {
  input: "softmax_int8"
  output: "softmax"
  name: ""
  type: "Int8Dequantize"
}
external_input: "data"
external_input: "conv0_conv_w_int8"
external_input: "conv0_bn_b_int8"
external_input: "xif0_0_pw_conv_w_int8"
external_input: "xif0_0_pw_bn_b_int8"
external_input: "xif0_0_dw_conv_w_int8"
external_input: "b_zero_generated_xif0_0_pw_int8"
external_input: "xif0_0_pwl_conv_w_int8"
external_input: "xif0_0_pwl_bn_b_int8"
external_input: "xif1_0_pw_conv_w_int8"
external_input: "xif1_0_pw_bn_b_int8"
external_input: "xif1_0_dw_conv_w_int8"
external_input: "b_zero_generated_xif1_0_pw_int8"
external_input: "xif1_0_conv_w_int8"
external_input: "xif1_0_bn_b_int8"
external_input: "xif2_0_pw_conv_w_int8"
external_input: "xif2_0_pw_bn_b_int8"
external_input: "xif2_0_dw_conv_w_int8"
external_input: "b_zero_generated_xif2_0_pw_int8"
external_input: "xif2_0_conv_w_int8"
external_input: "xif2_0_bn_b_int8"
external_input: "xif2_1_pw_conv_w_int8"
external_input: "xif2_1_pw_bn_b_int8"
external_input: "xif2_1_dw_conv_w_int8"
external_input: "b_zero_generated_xif2_1_pw_int8"
external_input: "xif2_1_pwl_conv_w_int8"
external_input: "xif2_1_pwl_bn_b_int8"
external_input: "xif2_2_pw_conv_w_int8"
external_input: "xif2_2_pw_bn_b_int8"
external_input: "xif2_2_dw_conv_w_int8"
external_input: "b_zero_generated_xif2_2_pw_int8"
external_input: "xif2_2_pwl_conv_w_int8"
external_input: "xif2_2_pwl_bn_b_int8"
external_input: "xif3_0_pw_conv_w_int8"
external_input: "xif3_0_pw_bn_b_int8"
external_input: "xif3_0_dw_conv_w_int8"
external_input: "b_zero_generated_xif3_0_pw_int8"
external_input: "xif3_0_conv_w_int8"
external_input: "xif3_0_bn_b_int8"
external_input: "xif3_1_pw_conv_w_int8"
external_input: "xif3_1_pw_bn_b_int8"
external_input: "xif3_1_dw_conv_w_int8"
external_input: "b_zero_generated_xif3_1_pw_int8"
external_input: "xif3_1_pwl_conv_w_int8"
external_input: "xif3_1_pwl_bn_b_int8"
external_input: "xif3_2_pw_conv_w_int8"
external_input: "xif3_2_pw_bn_b_int8"
external_input: "xif3_2_dw_conv_w_int8"
external_input: "b_zero_generated_xif3_2_pw_int8"
external_input: "xif3_2_pwl_conv_w_int8"
external_input: "xif3_2_pwl_bn_b_int8"
external_input: "xif3_3_pw_conv_w_int8"
external_input: "xif3_3_pw_bn_b_int8"
external_input: "xif3_3_dw_conv_w_int8"
external_input: "b_zero_generated_xif3_3_pw_int8"
external_input: "xif3_3_pwl_conv_w_int8"
external_input: "xif3_3_pwl_bn_b_int8"
external_input: "xif4_0_pw_conv_w_int8"
external_input: "xif4_0_pw_bn_b_int8"
external_input: "xif4_0_dw_conv_w_int8"
external_input: "b_zero_generated_xif4_0_pw_int8"
external_input: "xif4_0_conv_w_int8"
external_input: "xif4_0_bn_b_int8"
external_input: "xif4_1_pw_conv_w_int8"
external_input: "xif4_1_pw_bn_b_int8"
external_input: "xif4_1_dw_conv_w_int8"
external_input: "b_zero_generated_xif4_1_pw_int8"
external_input: "xif4_1_pwl_conv_w_int8"
external_input: "xif4_1_pwl_bn_b_int8"
external_input: "xif4_2_pw_conv_w_int8"
external_input: "xif4_2_pw_bn_b_int8"
external_input: "xif4_2_dw_conv_w_int8"
external_input: "b_zero_generated_xif4_2_pw_int8"
external_input: "xif4_2_conv_w_int8"
external_input: "xif4_2_bn_b_int8"
external_input: "xif4_2_bn_1x1_conv_w_int8"
external_input: "xif4_2_bn_1x1_bn_b_int8"
external_input: "pred_w_int8"
external_input: "pred_b_int8"
external_output: "softmax"
