name: "mobile_vision.cls_int8_1"
op {
  input: "data"
  output: "data_NHWC"
  name: ""
  type: "NCHW2NHWC"
}
op {
  input: "data_NHWC"
  output: "data_int8"
  name: ""
  type: "Int8Quantize"
  arg {
    name: "Y_scale"
    f: 0.0186584472656
  }
  arg {
    name: "Y_zero_point"
    i: 114
  }
}
op {
  input: "data_int8"
  input: "conv0_conv_w_int8"
  input: "conv0_bn_b_int8"
  output: "conv0_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.165592511275
  }
  device_option {
  }
  engine: ""
}
op {
  input: "conv0_int8"
  input: "fbn1_0_pw_conv_w_int8"
  input: "fbn1_0_pw_bn_b_int8"
  output: "fbn1_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.210400679961
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_0_pw_int8"
  input: "fbn1_0_dw_conv_w_int8"
  input: "fbn1_0_dw_bn_b_int8"
  output: "fbn1_0_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 48
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.221069195141
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_0_dw_int8"
  input: "fbn1_0_conv_w_int8"
  input: "fbn1_0_b_int8"
  output: "fbn1_0_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 153
  }
  arg {
    name: "Y_scale"
    f: 0.080042999866
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_0_int8"
  input: "fbn1_1_pw_conv_w_int8"
  input: "fbn1_1_pw_bn_b_int8"
  output: "fbn1_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0841659281906
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_1_pw_int8"
  input: "fbn1_1_dw_conv_w_int8"
  input: "fbn1_1_dw_bn_b_int8"
  output: "fbn1_1_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 24
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.144022112608
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_1_dw_int8"
  input: "fbn1_1_pwl_conv_w_int8"
  input: "fbn1_1_pwl_b_int8"
  output: "fbn1_1_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 132
  }
  arg {
    name: "Y_scale"
    f: 0.0634245704202
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_1_pwl_int8"
  input: "fbn1_0_int8"
  output: "fbn1_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0922384598676
  }
  arg {
    name: "Y_zero_point"
    i: 141
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn1_1_int8"
  input: "fbn2_0_pw_conv_w_int8"
  input: "fbn2_0_pw_bn_b_int8"
  output: "fbn2_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.189961256403
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_0_pw_int8"
  input: "fbn2_0_dw_conv_w_int8"
  input: "fbn2_0_dw_bn_b_int8"
  output: "fbn2_0_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 144
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.120784398907
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_0_dw_int8"
  input: "fbn2_0_conv_w_int8"
  input: "fbn2_0_b_int8"
  output: "fbn2_0_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 136
  }
  arg {
    name: "Y_scale"
    f: 0.0473817862716
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_0_int8"
  input: "fbn2_1_pw_conv_w_int8"
  input: "fbn2_1_pw_bn_b_int8"
  output: "fbn2_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0548192099249
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_1_pw_int8"
  input: "fbn2_1_dw_conv_w_int8"
  input: "fbn2_1_dw_bn_b_int8"
  output: "fbn2_1_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 96
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0866643051623
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_1_dw_int8"
  input: "fbn2_1_pwl_conv_w_int8"
  input: "fbn2_1_pwl_b_int8"
  output: "fbn2_1_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 128
  }
  arg {
    name: "Y_scale"
    f: 0.0480990615546
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_1_pwl_int8"
  input: "fbn2_0_int8"
  output: "fbn2_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0519372528675
  }
  arg {
    name: "Y_zero_point"
    i: 132
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_1_int8"
  input: "fbn2_2_pw_conv_w_int8"
  input: "fbn2_2_pw_bn_b_int8"
  output: "fbn2_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0622747612659
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_2_pw_int8"
  input: "fbn2_2_dw_conv_w_int8"
  input: "fbn2_2_dw_bn_b_int8"
  output: "fbn2_2_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 32
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0833306282862
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_2_dw_int8"
  input: "fbn2_2_pwl_conv_w_int8"
  input: "fbn2_2_pwl_b_int8"
  output: "fbn2_2_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 131
  }
  arg {
    name: "Y_scale"
    f: 0.0243514341467
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_2_pwl_int8"
  input: "fbn2_1_int8"
  output: "fbn2_2_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0552875668395
  }
  arg {
    name: "Y_zero_point"
    i: 133
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_2_int8"
  input: "fbn2_3_pw_conv_w_int8"
  input: "fbn2_3_pw_bn_b_int8"
  output: "fbn2_3_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0494833824571
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_3_pw_int8"
  input: "fbn2_3_dw_conv_w_int8"
  input: "fbn2_3_dw_bn_b_int8"
  output: "fbn2_3_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 96
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0950538216972
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_3_dw_int8"
  input: "fbn2_3_pwl_conv_w_int8"
  input: "fbn2_3_pwl_b_int8"
  output: "fbn2_3_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 84
  }
  arg {
    name: "Y_scale"
    f: 0.0418832330143
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_3_pwl_int8"
  input: "fbn2_2_int8"
  output: "fbn2_3_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0791304046032
  }
  arg {
    name: "Y_zero_point"
    i: 121
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn2_3_int8"
  input: "fbn3_0_pw_conv_w_int8"
  input: "fbn3_0_pw_bn_b_int8"
  output: "fbn3_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0910737273712
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_0_pw_int8"
  input: "fbn3_0_dw_conv_w_int8"
  input: "fbn3_0_dw_bn_b_int8"
  output: "fbn3_0_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 192
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.085457276869
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_0_dw_int8"
  input: "fbn3_0_conv_w_int8"
  input: "fbn3_0_b_int8"
  output: "fbn3_0_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 113
  }
  arg {
    name: "Y_scale"
    f: 0.0349888895072
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_0_int8"
  input: "fbn3_1_pw_conv_w_int8"
  input: "fbn3_1_pw_bn_b_int8"
  output: "fbn3_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0450345178331
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_1_pw_int8"
  input: "fbn3_1_dw_conv_w_int8"
  input: "fbn3_1_dw_bn_b_int8"
  output: "fbn3_1_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 192
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0698321858794
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_1_dw_int8"
  input: "fbn3_1_pwl_conv_w_int8"
  input: "fbn3_1_pwl_b_int8"
  output: "fbn3_1_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 103
  }
  arg {
    name: "Y_scale"
    f: 0.0340388578527
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_1_pwl_int8"
  input: "fbn3_0_int8"
  output: "fbn3_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0430555156633
  }
  arg {
    name: "Y_zero_point"
    i: 133
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_1_int8"
  input: "fbn3_2_pw_conv_w_int8"
  input: "fbn3_2_pw_bn_b_int8"
  output: "fbn3_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.214693170685
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_2_pw_int8"
  output: "fbn3_2_shuffle_int8"
  name: ""
  type: "Int8ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "Y_scale"
    f: 0.214693170685
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_2_shuffle_int8"
  input: "fbn3_2_dw_conv_w_int8"
  input: "fbn3_2_dw_bn_b_int8"
  output: "fbn3_2_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 64
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.04908916205
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_2_dw_int8"
  input: "fbn3_2_pwl_conv_w_int8"
  input: "fbn3_2_pwl_b_int8"
  output: "fbn3_2_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 145
  }
  arg {
    name: "Y_scale"
    f: 0.180891986922
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_2_pwl_int8"
  input: "fbn3_1_int8"
  output: "fbn3_2_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.190615470737
  }
  arg {
    name: "Y_zero_point"
    i: 137
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_2_int8"
  input: "fbn3_3_pw_conv_w_int8"
  input: "fbn3_3_pw_bn_b_int8"
  output: "fbn3_3_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0867498748791
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_3_pw_int8"
  input: "fbn3_3_dw_conv_w_int8"
  input: "fbn3_3_dw_bn_b_int8"
  output: "fbn3_3_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.242542162833
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_3_dw_int8"
  input: "fbn3_3_pwl_conv_w_int8"
  input: "fbn3_3_pwl_b_int8"
  output: "fbn3_3_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 120
  }
  arg {
    name: "Y_scale"
    f: 0.0851503409591
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_3_pwl_int8"
  input: "fbn3_2_int8"
  output: "fbn3_3_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.202779463226
  }
  arg {
    name: "Y_zero_point"
    i: 119
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_3_int8"
  input: "fbn3_4_pw_conv_w_int8"
  input: "fbn3_4_pw_bn_b_int8"
  output: "fbn3_4_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.156193202106
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_4_pw_int8"
  input: "fbn3_4_dw_conv_w_int8"
  input: "fbn3_4_dw_bn_b_int8"
  output: "fbn3_4_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 384
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.258180301935
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_4_dw_int8"
  input: "fbn3_4_conv_w_int8"
  input: "fbn3_4_b_int8"
  output: "fbn3_4_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 142
  }
  arg {
    name: "Y_scale"
    f: 0.0628511989818
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_4_int8"
  input: "fbn3_5_pw_conv_w_int8"
  input: "fbn3_5_pw_bn_b_int8"
  output: "fbn3_5_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.090996293094
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_5_pw_int8"
  output: "fbn3_5_shuffle_int8"
  name: ""
  type: "Int8ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "Y_scale"
    f: 0.090996293094
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_5_shuffle_int8"
  input: "fbn3_5_dw_conv_w_int8"
  input: "fbn3_5_dw_bn_b_int8"
  output: "fbn3_5_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 112
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.185141030986
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_5_dw_int8"
  input: "fbn3_5_pwl_conv_w_int8"
  input: "fbn3_5_pwl_b_int8"
  output: "fbn3_5_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 142
  }
  arg {
    name: "Y_scale"
    f: 0.054361261106
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_5_pwl_int8"
  input: "fbn3_4_int8"
  output: "fbn3_5_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0712709539077
  }
  arg {
    name: "Y_zero_point"
    i: 148
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_5_int8"
  input: "fbn3_6_pw_conv_w_int8"
  input: "fbn3_6_pw_bn_b_int8"
  output: "fbn3_6_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.112710113467
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_6_pw_int8"
  input: "fbn3_6_dw_conv_w_int8"
  input: "fbn3_6_dw_bn_b_int8"
  output: "fbn3_6_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 336
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.137552042972
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_6_dw_int8"
  input: "fbn3_6_pwl_conv_w_int8"
  input: "fbn3_6_pwl_b_int8"
  output: "fbn3_6_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 128
  }
  arg {
    name: "Y_scale"
    f: 0.0586996527279
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_6_pwl_int8"
  input: "fbn3_5_int8"
  output: "fbn3_6_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0861241957721
  }
  arg {
    name: "Y_zero_point"
    i: 149
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_6_int8"
  input: "fbn3_7_pw_conv_w_int8"
  input: "fbn3_7_pw_bn_b_int8"
  output: "fbn3_7_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0754606707616
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_7_pw_int8"
  output: "fbn3_7_shuffle_int8"
  name: ""
  type: "Int8ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "Y_scale"
    f: 0.0754606707616
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_7_shuffle_int8"
  input: "fbn3_7_dw_conv_w_int8"
  input: "fbn3_7_dw_bn_b_int8"
  output: "fbn3_7_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "group"
    i: 112
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.167522365478
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_7_dw_int8"
  input: "fbn3_7_pwl_conv_w_int8"
  input: "fbn3_7_pwl_b_int8"
  output: "fbn3_7_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 111
  }
  arg {
    name: "Y_scale"
    f: 0.0395954805262
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_7_pwl_int8"
  input: "fbn3_6_int8"
  output: "fbn3_7_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0709633696313
  }
  arg {
    name: "Y_zero_point"
    i: 141
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn3_7_int8"
  input: "fbn4_0_pw_conv_w_int8"
  input: "fbn4_0_pw_bn_b_int8"
  output: "fbn4_0_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 1.11435915339
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_0_pw_int8"
  input: "fbn4_0_dw_conv_w_int8"
  input: "fbn4_0_dw_bn_b_int8"
  output: "fbn4_0_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 672
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.169481408494
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_0_dw_int8"
  input: "fbn4_0_conv_w_int8"
  input: "fbn4_0_b_int8"
  output: "fbn4_0_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 111
  }
  arg {
    name: "Y_scale"
    f: 0.0438304751527
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_0_int8"
  input: "fbn4_1_pw_conv_w_int8"
  input: "fbn4_1_pw_bn_b_int8"
  output: "fbn4_1_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.0882771622168
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_1_pw_int8"
  input: "fbn4_1_dw_conv_w_int8"
  input: "fbn4_1_dw_bn_b_int8"
  output: "fbn4_1_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 1104
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.113849878953
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_1_dw_int8"
  input: "fbn4_1_pwl_conv_w_int8"
  input: "fbn4_1_pwl_b_int8"
  output: "fbn4_1_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 142
  }
  arg {
    name: "Y_scale"
    f: 0.0385647755043
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_1_pwl_int8"
  input: "fbn4_0_int8"
  output: "fbn4_1_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0611079085107
  }
  arg {
    name: "Y_zero_point"
    i: 117
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_1_int8"
  input: "fbn4_2_pw_conv_w_int8"
  input: "fbn4_2_pw_bn_b_int8"
  output: "fbn4_2_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.235674446924
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_2_pw_int8"
  input: "fbn4_2_dw_conv_w_int8"
  input: "fbn4_2_dw_bn_b_int8"
  output: "fbn4_2_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 552
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.133856767877
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_2_dw_int8"
  input: "fbn4_2_pwl_conv_w_int8"
  input: "fbn4_2_pwl_b_int8"
  output: "fbn4_2_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 144
  }
  arg {
    name: "Y_scale"
    f: 0.046710025563
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_2_pwl_int8"
  input: "fbn4_1_int8"
  output: "fbn4_2_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0678422591266
  }
  arg {
    name: "Y_zero_point"
    i: 122
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_2_int8"
  input: "fbn4_3_pw_conv_w_int8"
  input: "fbn4_3_pw_bn_b_int8"
  output: "fbn4_3_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.169848643372
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_3_pw_int8"
  input: "fbn4_3_dw_conv_w_int8"
  input: "fbn4_3_dw_bn_b_int8"
  output: "fbn4_3_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 1104
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.137666961776
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_3_dw_int8"
  input: "fbn4_3_pwl_conv_w_int8"
  input: "fbn4_3_pwl_b_int8"
  output: "fbn4_3_pwl_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 137
  }
  arg {
    name: "Y_scale"
    f: 0.0983851114909
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_3_pwl_int8"
  input: "fbn4_2_int8"
  output: "fbn4_3_int8"
  name: ""
  type: "Int8Sum"
  arg {
    name: "Y_scale"
    f: 0.0856662226658
  }
  arg {
    name: "Y_zero_point"
    i: 156
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_3_int8"
  input: "fbn4_4_pw_conv_w_int8"
  input: "fbn4_4_pw_bn_b_int8"
  output: "fbn4_4_pw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.147977933081
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_4_pw_int8"
  input: "fbn4_4_dw_conv_w_int8"
  input: "fbn4_4_dw_bn_b_int8"
  output: "fbn4_4_dw_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "group"
    i: 1104
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 2
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.156708750653
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_4_dw_int8"
  input: "fbn4_4_conv_w_int8"
  input: "fbn4_4_b_int8"
  output: "fbn4_4_int8"
  name: ""
  type: "Int8Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 126
  }
  arg {
    name: "Y_scale"
    f: 0.0299797095504
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_4_int8"
  input: "fbn4_4_1x1_conv_w_int8"
  input: "fbn4_4_1x1_bn_b_int8"
  output: "fbn4_4_1x1_int8"
  name: ""
  type: "Int8ConvRelu"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  arg {
    name: "Y_scale"
    f: 0.226853345543
  }
  device_option {
  }
  engine: ""
}
op {
  input: "fbn4_4_1x1_int8"
  output: "final_avg_int8"
  name: ""
  type: "Int8AveragePool"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "kernel"
    i: 7
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_scale"
    f: 0.226853345543
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  device_option {
  }
  engine: ""
}
op {
  input: "final_avg_int8"
  input: "pred_w_int8"
  input: "pred_b_int8"
  output: "pred_int8"
  name: ""
  type: "Int8FC"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_zero_point"
    i: 76
  }
  arg {
    name: "Y_scale"
    f: 0.189985985849
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pred_int8"
  output: "softmax_int8"
  name: ""
  type: "Int8Softmax"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "Y_scale"
    f: 0.00390625
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
  device_option {
  }
  engine: ""
}
op {
  input: "softmax_int8"
  output: "softmax"
  name: ""
  type: "Int8Dequantize"
}
external_input: "data"
external_input: "conv0_conv_w_int8"
external_input: "conv0_bn_b_int8"
external_input: "fbn1_0_pw_conv_w_int8"
external_input: "fbn1_0_pw_bn_b_int8"
external_input: "fbn1_0_dw_conv_w_int8"
external_input: "fbn1_0_dw_bn_b_int8"
external_input: "fbn1_0_conv_w_int8"
external_input: "fbn1_0_b_int8"
external_input: "fbn1_1_pw_conv_w_int8"
external_input: "fbn1_1_pw_bn_b_int8"
external_input: "fbn1_1_dw_conv_w_int8"
external_input: "fbn1_1_dw_bn_b_int8"
external_input: "fbn1_1_pwl_conv_w_int8"
external_input: "fbn1_1_pwl_b_int8"
external_input: "fbn2_0_pw_conv_w_int8"
external_input: "fbn2_0_pw_bn_b_int8"
external_input: "fbn2_0_dw_conv_w_int8"
external_input: "fbn2_0_dw_bn_b_int8"
external_input: "fbn2_0_conv_w_int8"
external_input: "fbn2_0_b_int8"
external_input: "fbn2_1_pw_conv_w_int8"
external_input: "fbn2_1_pw_bn_b_int8"
external_input: "fbn2_1_dw_conv_w_int8"
external_input: "fbn2_1_dw_bn_b_int8"
external_input: "fbn2_1_pwl_conv_w_int8"
external_input: "fbn2_1_pwl_b_int8"
external_input: "fbn2_2_pw_conv_w_int8"
external_input: "fbn2_2_pw_bn_b_int8"
external_input: "fbn2_2_dw_conv_w_int8"
external_input: "fbn2_2_dw_bn_b_int8"
external_input: "fbn2_2_pwl_conv_w_int8"
external_input: "fbn2_2_pwl_b_int8"
external_input: "fbn2_3_pw_conv_w_int8"
external_input: "fbn2_3_pw_bn_b_int8"
external_input: "fbn2_3_dw_conv_w_int8"
external_input: "fbn2_3_dw_bn_b_int8"
external_input: "fbn2_3_pwl_conv_w_int8"
external_input: "fbn2_3_pwl_b_int8"
external_input: "fbn3_0_pw_conv_w_int8"
external_input: "fbn3_0_pw_bn_b_int8"
external_input: "fbn3_0_dw_conv_w_int8"
external_input: "fbn3_0_dw_bn_b_int8"
external_input: "fbn3_0_conv_w_int8"
external_input: "fbn3_0_b_int8"
external_input: "fbn3_1_pw_conv_w_int8"
external_input: "fbn3_1_pw_bn_b_int8"
external_input: "fbn3_1_dw_conv_w_int8"
external_input: "fbn3_1_dw_bn_b_int8"
external_input: "fbn3_1_pwl_conv_w_int8"
external_input: "fbn3_1_pwl_b_int8"
external_input: "fbn3_2_pw_conv_w_int8"
external_input: "fbn3_2_pw_bn_b_int8"
external_input: "fbn3_2_dw_conv_w_int8"
external_input: "fbn3_2_dw_bn_b_int8"
external_input: "fbn3_2_pwl_conv_w_int8"
external_input: "fbn3_2_pwl_b_int8"
external_input: "fbn3_3_pw_conv_w_int8"
external_input: "fbn3_3_pw_bn_b_int8"
external_input: "fbn3_3_dw_conv_w_int8"
external_input: "fbn3_3_dw_bn_b_int8"
external_input: "fbn3_3_pwl_conv_w_int8"
external_input: "fbn3_3_pwl_b_int8"
external_input: "fbn3_4_pw_conv_w_int8"
external_input: "fbn3_4_pw_bn_b_int8"
external_input: "fbn3_4_dw_conv_w_int8"
external_input: "fbn3_4_dw_bn_b_int8"
external_input: "fbn3_4_conv_w_int8"
external_input: "fbn3_4_b_int8"
external_input: "fbn3_5_pw_conv_w_int8"
external_input: "fbn3_5_pw_bn_b_int8"
external_input: "fbn3_5_dw_conv_w_int8"
external_input: "fbn3_5_dw_bn_b_int8"
external_input: "fbn3_5_pwl_conv_w_int8"
external_input: "fbn3_5_pwl_b_int8"
external_input: "fbn3_6_pw_conv_w_int8"
external_input: "fbn3_6_pw_bn_b_int8"
external_input: "fbn3_6_dw_conv_w_int8"
external_input: "fbn3_6_dw_bn_b_int8"
external_input: "fbn3_6_pwl_conv_w_int8"
external_input: "fbn3_6_pwl_b_int8"
external_input: "fbn3_7_pw_conv_w_int8"
external_input: "fbn3_7_pw_bn_b_int8"
external_input: "fbn3_7_dw_conv_w_int8"
external_input: "fbn3_7_dw_bn_b_int8"
external_input: "fbn3_7_pwl_conv_w_int8"
external_input: "fbn3_7_pwl_b_int8"
external_input: "fbn4_0_pw_conv_w_int8"
external_input: "fbn4_0_pw_bn_b_int8"
external_input: "fbn4_0_dw_conv_w_int8"
external_input: "fbn4_0_dw_bn_b_int8"
external_input: "fbn4_0_conv_w_int8"
external_input: "fbn4_0_b_int8"
external_input: "fbn4_1_pw_conv_w_int8"
external_input: "fbn4_1_pw_bn_b_int8"
external_input: "fbn4_1_dw_conv_w_int8"
external_input: "fbn4_1_dw_bn_b_int8"
external_input: "fbn4_1_pwl_conv_w_int8"
external_input: "fbn4_1_pwl_b_int8"
external_input: "fbn4_2_pw_conv_w_int8"
external_input: "fbn4_2_pw_bn_b_int8"
external_input: "fbn4_2_dw_conv_w_int8"
external_input: "fbn4_2_dw_bn_b_int8"
external_input: "fbn4_2_pwl_conv_w_int8"
external_input: "fbn4_2_pwl_b_int8"
external_input: "fbn4_3_pw_conv_w_int8"
external_input: "fbn4_3_pw_bn_b_int8"
external_input: "fbn4_3_dw_conv_w_int8"
external_input: "fbn4_3_dw_bn_b_int8"
external_input: "fbn4_3_pwl_conv_w_int8"
external_input: "fbn4_3_pwl_b_int8"
external_input: "fbn4_4_pw_conv_w_int8"
external_input: "fbn4_4_pw_bn_b_int8"
external_input: "fbn4_4_dw_conv_w_int8"
external_input: "fbn4_4_dw_bn_b_int8"
external_input: "fbn4_4_conv_w_int8"
external_input: "fbn4_4_b_int8"
external_input: "fbn4_4_1x1_conv_w_int8"
external_input: "fbn4_4_1x1_bn_b_int8"
external_input: "pred_w_int8"
external_input: "pred_b_int8"
external_output: "softmax"
